const { Prisma } = require('@prisma/client');

const dataList = [
  { img_url: '/images/food/1.webp', img_name: '짜파게티', win_count: 0 },
  { img_url: '/images/food/2.webp', img_name: '후라이드 치킨', win_count: 0 },
  { img_url: '/images/food/3.webp', img_name: '피자', win_count: 0 },
  { img_url: '/images/food/4.webp', img_name: '제육볶음', win_count: 0 },
  { img_url: '/images/food/5.webp', img_name: '샤브샤브', win_count: 0 },
  { img_url: '/images/food/6.webp', img_name: '떡볶이', win_count: 0 },
  { img_url: '/images/food/7.webp', img_name: '냉면', win_count: 0 },
  { img_url: '/images/food/8.webp', img_name: '소떡소떡', win_count: 0 },
  { img_url: '/images/food/9.webp', img_name: '토마토 파스타', win_count: 0 },
  { img_url: '/images/food/10.webp', img_name: '스테이크', win_count: 0 },
  {
    img_url: '/images/food/11.webp',
    img_name: '립아이 스테이크',
    win_count: 0,
  },
  { img_url: '/images/food/12.webp', img_name: '초밥', win_count: 0 },
  { img_url: '/images/food/13.webp', img_name: '김밥', win_count: 0 },
  { img_url: '/images/food/14.webp', img_name: '햄버거', win_count: 0 },
  { img_url: '/images/food/15.webp', img_name: '순두부찌개', win_count: 0 },
  { img_url: '/images/food/16.webp', img_name: '간장게장', win_count: 0 },
  { img_url: '/images/food/17.webp', img_name: '타코야끼', win_count: 0 },
  { img_url: '/images/food/18.webp', img_name: '소갈비', win_count: 0 },
  { img_url: '/images/food/19.webp', img_name: '커리', win_count: 0 },
  { img_url: '/images/food/20.webp', img_name: '비프 스튜', win_count: 0 },
  { img_url: '/images/food/21.webp', img_name: '짜장면', win_count: 0 },
  { img_url: '/images/food/22.webp', img_name: '짬뽕', win_count: 0 },
  { img_url: '/images/food/23.webp', img_name: '탕수육', win_count: 0 },
  { img_url: '/images/food/24.webp', img_name: '오무라이스', win_count: 0 },
  { img_url: '/images/food/25.webp', img_name: '꼬치구이', win_count: 0 },
  { img_url: '/images/food/26.webp', img_name: '돈코츠 라멘', win_count: 0 },
  { img_url: '/images/food/27.webp', img_name: '오렌지 치킨', win_count: 0 },
  { img_url: '/images/food/28.webp', img_name: '볶음밥', win_count: 0 },
  { img_url: '/images/food/29.webp', img_name: '만두', win_count: 0 },
  { img_url: '/images/food/30.webp', img_name: '콘치즈', win_count: 0 },
  { img_url: '/images/food/31.webp', img_name: '돈까스', win_count: 0 },
  { img_url: '/images/food/32.webp', img_name: '계란 샌드위치', win_count: 0 },
  {
    img_url: '/images/food/33.webp',
    img_name: '길거리 샌드위치',
    win_count: 0,
  },
  { img_url: '/images/food/34.webp', img_name: '소세지', win_count: 0 },
  { img_url: '/images/food/35.webp', img_name: '치킨마요', win_count: 0 },
  { img_url: '/images/food/36.webp', img_name: '묵국', win_count: 0 },
  { img_url: '/images/food/37.webp', img_name: '사시미', win_count: 0 },
  { img_url: '/images/food/38.webp', img_name: '잡채', win_count: 0 },
  { img_url: '/images/food/39.webp', img_name: '수육국밥', win_count: 0 },
  { img_url: '/images/food/40.webp', img_name: '육회', win_count: 0 },
  { img_url: '/images/food/41.webp', img_name: '족발', win_count: 0 },
  { img_url: '/images/food/42.webp', img_name: '누룽지탕', win_count: 0 },
  { img_url: '/images/food/43.webp', img_name: '조개 술찜', win_count: 0 },
  { img_url: '/images/food/44.webp', img_name: '쌀국수', win_count: 0 },
  { img_url: '/images/food/45.webp', img_name: '로스트 비프', win_count: 0 },
  { img_url: '/images/food/46.webp', img_name: '전복죽', win_count: 0 },
  { img_url: '/images/food/47.webp', img_name: '연어 스테이크', win_count: 0 },
  { img_url: '/images/food/48.webp', img_name: '장어구이', win_count: 0 },
  { img_url: '/images/food/49.webp', img_name: '똠얌꿍', win_count: 0 },
  { img_url: '/images/food/50.webp', img_name: '치즈볼', win_count: 0 },
  { img_url: '/images/food/51.webp', img_name: '양꼬치', win_count: 0 },
  { img_url: '/images/food/52.webp', img_name: '부대찌게', win_count: 0 },
  { img_url: '/images/food/53.webp', img_name: '핫도그', win_count: 0 },
  { img_url: '/images/food/54.webp', img_name: '마파두부', win_count: 0 },
  {
    img_url: '/images/food/55.webp',
    img_name: '아스파라거스 롤',
    win_count: 0,
  },
  { img_url: '/images/food/56.webp', img_name: '애플파이', win_count: 0 },
  { img_url: '/images/food/57.webp', img_name: '크루아상', win_count: 0 },
  { img_url: '/images/food/58.webp', img_name: '맥앤치즈', win_count: 0 },
  { img_url: '/images/food/59.webp', img_name: '우동', win_count: 0 },
  { img_url: '/images/food/60.webp', img_name: '계란말이', win_count: 0 },
  { img_url: '/images/food/61.webp', img_name: '미고렝', win_count: 0 },
  { img_url: '/images/food/62.webp', img_name: '새우튀김', win_count: 0 },
  { img_url: '/images/food/63.webp', img_name: '핫케이크', win_count: 0 },
  { img_url: '/images/food/64.webp', img_name: '크레페', win_count: 0 },
  { img_url: '/images/food/65.webp', img_name: '샐러드 파스타', win_count: 0 },
  { img_url: '/images/food/66.webp', img_name: '부리또', win_count: 0 },
  { img_url: '/images/food/66.webp', img_name: '베이컨말이', win_count: 0 },
  { img_url: '/images/food/66.webp', img_name: '도넛', win_count: 0 },
  { img_url: '/images/food/66.webp', img_name: '부리또', win_count: 0 },
];

export default dataList;
